### ISSUE TITLE
Error loading list of services when running on the worker node

### ISSUE THREAD

**Issue by elyulka** [neuroforgede/docker-engine-networks-exporter#4]
I've noticed errors in logs:
```
Apr 15 18:15:51 staging-devops1 dockerd[3457426]: time="2024-04-15T18:15:51.942700635Z" level=error msg="Handler for GET /v1.45/services returned error: This node is not a swarm manager. Worker nodes can't be used to view or modify cluster state. Please run this comman
d on a manager node or promote the current node to a manager." spanID=7fba43868a36c4df traceID=7bf2d2b305150245226324871cfeb6f2
```

And found it's loading list of services from the current node here:
[network_exporter_prom.py#L172](https://github.com/neuroforgede/docker-engine-networks-exporter/blob/master/docker/network_exporter_prom.py#L172)

But when deployed globally and being run on the worker node swarm api is not accessible, it should load services from the manager node.

**Comment by s4ke** [comment]
To be honest, this is working as originally intended when I wrote this exporter.

Maybe we should add a detection if we are running on a manager and if not, disable the service related calls altogether for this node.

**Comment by elyulka** [comment]
Oh, i see you handle this case. Sorry for disturbing.
